language: csharp
sudo: required 
dist: trusty
mono: none
dotnet: 2.1.402
install:
- dotnet restore
script:
- dotnet build
- dotnet test HwProj.CoursesService/HwProj.CoursesService.Tests/HwProj.CoursesService.Tests.csproj
